name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
